### ISSUE TITLE
Thread blocking

### ISSUE THREAD

**Issue by NickMortimer** [katsyoshi/fluent-plugin-serialport#7]
Hi I'm trying to use this plugin to get data from a usb serial port and keep getting this when a eol char is received 

/var/lib/gems/2.5.0/gems/fluent-plugin-serialport-0.14.1/lib/fluent/plugin/in_serialport.rb:35:in `block in run'
/var/lib/gems/2.5.0/gems/fluent-plugin-serialport-0.14.1/lib/fluent/plugin/in_serialport.rb:33:in `loop'
/var/lib/gems/2.5.0/gems/fluent-plugin-serialport-0.14.1/lib/fluent/plugin/in_serialport.rb:33:in `run'
/var/lib/gems/2.5.0/gems/fluentd-1.2.1/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'

**Comment by NickMortimer** [comment]
OK I think I have the solution! Sorry I'm new to all this but 

router.emit(@tag, Fluent::EventTime.now, data)

instead of 

router.emit(@tag, Engine.now, data)

**Comment by katsyoshi** [comment]
Oh...This is a bug.
Thank you teach me the bug.
Could you create PR that it fixed?

**Comment by NickMortimer** [comment]
Yep that fixed it. But I think there are some other issues, most of the time I'm using GPS feed every 2s so it times out. Had to do a little fix for the will do a pull request in the morning!

**Comment by katsyoshi** [comment]
oh, sorry.
I merged PR#8 that fixed this bug.
Could you try new version of 1.0.0?
